name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - uses: actions/checkout@v1
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        version: 12

    - name: yarn install, yarn lint, yarn test, yarn build
      run: |
        yarn install
        yarn lint
        yarn test
        yarn build
    - name: rsync deployments
      uses: contention/rsync-deployments@v1.0.0
      env: 
        DEPLOY_KEY: ${{secrets.DEPLOY_KEY}} 
      with: 
        args: "-avzr --delete --exclude .htaccess --exclude /uploads/ root@139.162.6.235:/var/www/test/"
