name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - uses: actions/checkout@v1
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        version: 12

#     - name: yarn install, yarn lint, yarn test, yarn build
#       run: |
#         yarn install
#         yarn lint
#         yarn test
#         yarn build
    - uses: actions/checkout@v1
    - name: rsync deployments
      uses: burnett01/rsync-deployments@3.0
      with:
        switches: -avzr --delete
        path: public/
        remote_path: /var/www/test/
        remote_host: 139.162.6.235
        remote_user: root
        remote_key: ${{ secrets.DEPLOY_KEY }}
